### ISSUE TITLE
Add Support for Pipenv

### ISSUE THREAD

**Issue by deadmau6** [connorjoleary/DeepCite#15]
Hi, I was just wondering if we can put in a small feature request for those of us that use `pipenv`.  `pipenv` just generates some extra files like a `Pipfile` and `Pipfile.lock`. So I think adding support for `pipenv` would be as simple as adding these files to the `.gitignore` so that way `pipenv` users don't have to worry about accidentally pushing these files. Also can I take this issue?

**Comment by connorjoleary** [comment]
This would also be great. Thank you!
