### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by deadmau6** [connorjoleary/DeepCite#16]
When installing and running I noticed that some of the `readme` instructions are a little lacking. For example, the install for `word2vec` is a little unclear because I noticed that the backend only requires the pretrained model and not the complete code but we can easily expand those instructions with a few extra bullet points on how to download the pretrained model. Also I would like to add a short instruction on how to install on `firefox`. Could I take this issue?

**Comment by connorjoleary** [comment]
Yes please, thank you! Just start the branch with your name and short description. Then I'll approve and merge
