### ISSUE TITLE
Add user feedback to approve or disapprove the result

### ISSUE THREAD

**Issue by connorjoleary** [connorjoleary/DeepCite#28]

**Comment by deadmau6** [comment]
Is the feed back going to be binary? Or have you considered a rank like 5/10?

**Comment by connorjoleary** [comment]
I'm thinking binary because in my mind the algorithm either gets it, or it doesn't. And then hopefully in the future if you ever them didn't get it, we would gather feedback on why it missed.

**Comment by connorjoleary** [comment]
I'm open to trying a ranking, but I fear that the ranks will be more based upon the information found on the website, and less on the performance of the algorithm

**Comment by connorjoleary** [comment]
Maybe best to only use a thumbs up instead of two arrows. Confusing to have arrows because they imply that the box is moving.
