### ISSUE TITLE
Improve error handling 

### ISSUE THREAD

**Issue by connorjoleary** [connorjoleary/DeepCite#45]
right now this response is not send to the user, nor is any other error
`    except Exception as e:
        if check_instance(e):
            full_pre_json['error'] = str(e)
        else:
            link = html_link('https://github.com/connorjoleary/DeepCite/issues')
            full_pre_json['error'] = str('Error 500: Internal Server Error ' + str(e) + "."  + \
                        new_indention("Please add your error to " + link + " with the corresponding claim and link."))`

if we do want to show users errors we need to improve what they say.

**Comment by deadmau6** [comment]
Is this still an issue, if so could I take this one? ( I know it is for beginners but I am still reading throw and trying to understand the backend)
